/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementCard: typeof import('./components/AnnouncementCard.vue')['default']
    AnnouncementCreateDialog: typeof import('./components/AnnouncementCreateDialog.vue')['default']
    AnnouncementEditDialog: typeof import('./components/AnnouncementEditDialog.vue')['default']
    BirthDateDialog: typeof import('./components/BirthDateDialog.vue')['default']
    BlogCard: typeof import('./components/BlogCard.vue')['default']
    BlogEditTemplate: typeof import('./components/BlogEditTemplate.vue')['default']
    BlogList: typeof import('./components/BlogList.vue')['default']
    CommonAdminTemplate: typeof import('./components/CommonAdminTemplate.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader.vue')['default']
    CommonLoginTemplate: typeof import('./components/CommonLoginTemplate.vue')['default']
    CommonSidemenu: typeof import('./components/CommonSidemenu.vue')['default']
    CommonTemplate: typeof import('./components/CommonTemplate.vue')['default']
    CommonUsermenu: typeof import('./components/CommonUsermenu.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MomentCard: typeof import('./components/MomentCard.vue')['default']
    MomentCreateDialog: typeof import('./components/MomentCreateDialog.vue')['default']
    MomentForm: typeof import('./components/MomentForm.vue')['default']
    MomentViewer: typeof import('./components/MomentViewer.vue')['default']
    NotificationDialog: typeof import('./components/NotificationDialog.vue')['default']
    ReblogTemplate: typeof import('./components/ReblogTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TweetCard: typeof import('./components/TweetCard.vue')['default']
    TweetCreateDialog: typeof import('./components/TweetCreateDialog.vue')['default']
    TweetEditDialog: typeof import('./components/TweetEditDialog.vue')['default']
    TweetList: typeof import('./components/TweetList.vue')['default']
    TweetPreviewDialog: typeof import('./components/TweetPreviewDialog.vue')['default']
  }
}
