/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementCreateDialog: typeof import('./components/AnnouncementCreateDialog.vue')['default']
    AnnouncementEditDialog: typeof import('./components/AnnouncementEditDialog.vue')['default']
    BirthDateDialog: typeof import('./components/BirthDateDialog.vue')['default']
    BlogCard: typeof import('./components/BlogCard.vue')['default']
    BlogEditTemplate: typeof import('./components/BlogEditTemplate.vue')['default']
    BlogList: typeof import('./components/BlogList.vue')['default']
    CommonAdminTemplate: typeof import('./components/CommonAdminTemplate.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader.vue')['default']
    CommonLoginTemplate: typeof import('./components/CommonLoginTemplate.vue')['default']
    CommonSidemenu: typeof import('./components/CommonSidemenu.vue')['default']
    CommonTemplate: typeof import('./components/CommonTemplate.vue')['default']
    CommonUsermenu: typeof import('./components/CommonUsermenu.vue')['default']
    DialogTemplate: typeof import('./components/DialogTemplate.vue')['default']
    FollowListDialog: typeof import('./components/FollowListDialog.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MomentCard: typeof import('./components/MomentCard.vue')['default']
    MomentForm: typeof import('./components/MomentForm.vue')['default']
    NotificationDialog: typeof import('./components/NotificationDialog.vue')['default']
    ReblogTemplate: typeof import('./components/ReblogTemplate.vue')['default']
    ResetPasswordConfirmDialog: typeof import('./components/ResetPasswordConfirmDialog.vue')['default']
    ResetPasswordDialog: typeof import('./components/ResetPasswordDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TweetCard: typeof import('./components/TweetCard.vue')['default']
    TweetCreateDialog: typeof import('./components/TweetCreateDialog.vue')['default']
    TweetList: typeof import('./components/TweetList.vue')['default']
    UserCreateDialog: typeof import('./components/UserCreateDialog.vue')['default']
  }
}
